### ISSUE TITLE
Vulnerability caused by dependency to`request`.

### ISSUE THREAD

**Issue by greenluca** [luzmo-official/luzmo-sdk-nodejs#7]
Hello,
we are currently facing an issue due to the vulnerability on this package, caused by the outdated version of your dependency to `request`, here's the graph
* cumulio@1.1.0
* request@2.88.0
* http-signature@1.2.0 (obsolete)
* jsprim "^1.2.2” (obsolete)
* json-schema "0.2.3” (obsolete and vulnerable)

[`request` has been discontinued in 2019](https://github.com/request/request/issues/3142) so we guess their dependencies will not be updated anymore. We strongly encourage you to find an alternative to `request` (like Axios, for example) in order to keep your ecosystem up-to-date with security patches.
Otherwise, we will have to find an alternative to Cumul.io.

**Comment by gaelperon** [comment]
Up

**Comment by jooststessens** [comment]
Hi @greenluca and @gaelperon, thanks for creating this issue and following up on it!

We'd like to first of all sincerely apologize for the delayed response. We're aligning internally to improve coverage of our public repositories to avoid this in the future. 
As of now, we've merged [this PR](https://github.com/luzmo-official/luzmo-sdk-nodejs/pull/9) and released [version 1.2.0 of our Node.js SDK on NPM](https://www.npmjs.com/package/@luzmo/nodejs-sdk/v/1.2.0) earlier today; in here, we are using `axios` instead of `request`. If you encounter any further issues, please don't hesitate to let us know by opening a new issue or reaching out to our support team at [support@luzmo.com](support@luzmo.com).

Once again, we apologize for the delay, and we appreciate your patience and understanding!

**Comment by gaelperon** [comment]
Thank you for your quick response.

You can activate Dependabot inside github to check for vulnerabilities. It's very useful
